# Generated by Django 4.0 on 2024-01-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.IntegerField(choices=[(1, 'user'), (2, 'manager'), (3, 'admin')], default=1),
        ),
    ]
